{% set name = "isal" %}
{% set version = "0.11.1" %}

package:
  name: python-isal    # To avoid confusion with isa-l proper
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d07a07caacc3be4f478ceff8353941f360f922e8854ff1cbee4a44b443eb2af

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - PYTHON_ISAL_LINK_DYNAMIC=true  # Forces a dynamic link against isa-l in conda-forge

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - isa-l
    - python
    - pip
    - cython  # Cython and setuptools are also required in pyproject.toml
    - setuptools
  run:
    - python
    - isa-l >=2.26
test:
  imports:
    - isal
  commands:
    - python -c "from isal import igzip"
    - python -c "from isal import isal_zlib; isal_zlib.adler32(b'test')"

about:
  home: https://github.com/pycompression/python-isal
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Faster zlib and gzip compatible compression and decompression by providing python bindings for the isa-l library.
  doc_url: https://python-isal.readthedocs.io
  dev_url: https://github.com/pycompression/python-isal

extra:
  recipe-maintainers:
    - rhpvorderman
